<link rel="stylesheet" href="/css/help.css" type="text/css" media="screen"/>
<script type="text/javascript" src="/js/help.js"></script>	


<div id="help_wrap">





<h1>Help section outline</h1><hr>
<div id="help_div">
<ul>
<li><a href="#intro">Basic Information</a></li>
<li><a href="#navigation">Navigation</a></li>
<li><a href="#howto">How To</a></li>
</ul>
<div id="intro">
<h3>Introduction</h3>
		<p>This Portal connects the international managers that maintain the Return and Refurbish Partners that work with LenovoEMC Products.  This portal tracks the LenovoEMC products using the RMA system to maintain and understand the product life-cycle.  RMAs can be searched and edited by any user for the particular site or by any manager with the site access.</p>
		<br>
		<p>The Portal also enables managers to monitor the total inventory for their managed sites.   Managers can see when they need to redistribute any inventory item between the partners using the reports generated by the Inventory Tracking System.  Managers can also add in lead times in to the Inventory Reporting to help calculate how much time inventory changes should take at each site.</p>
		<br>
		<p>The Learning Center serves as a repository for product specific information and well as host rules and regulations for the partners to access.  New items can be added and removed from the list of resources by any administrator of the site.</p>
</div>
<div id="navigation">
<h3>Top banner</h3>
<p>(HOME,RMA, Inventory, Learning Center, User Manager, and Logout)</p>
<h3>Side menu</h3>
<p>RMA (Create New, Search RMA's, Manager Search RMA), Learning Center, Inventory, Search Inventory</p>
<h3>Messaging</h3>
<p>Messages are displayed to the user on the home page.</p>
</div>
<div id="howto">
<h3>Creating a new RMA</h3><p>(open site &rarr; click on rma &rarr; fill out information for rma (managers will have to edit the site information)</p>
<h3>Editing a RMA</h3> <p>(open site &rarr; click on search rma's &rarr; search for rma you want to edit &rarr;
click on the rma # in the search results &rarr; make changes to the RMA &rarr;
click on the save button )<p>

<h3>Manager Searching and Reporting</h3><p>(open site &rarr; click on manager search rma &rarr;
all rma's for the manager's site will appear, as well as a search filter &rarr;
mangers can filter the searches for either visual or CSV download</p>

<h3>Learning Center</h3>
<p>Click on the filename to download the file</p>

<h3>User Manager</h3>
<p>Click on a user's Email address to edit a user &rarr; Change permissions and site information for the user &rarr; submit changes</p>


<h3>Inventory</h3>
<p>Input Weekly Inventory Reports in csv format.</p>
<p>Search on Inputed Inventory Reports.</p>
<br/>
<p>To upload your inventory report,  Click on &quot;Inventory&quot;, click on todays date, make sure your site code is correct, upload your inventory as a CSV file, 
The file should be a comma delimited file in order of: Quantity,Part number,HD type,Site,Location,Part description,Oracle description
</p>


<h3>Logout</h3>
<p>Click on the Logout link to end your session on the LenovoEMC Reverse Logistics Portal</p>
 

</div></div></div>